extends "res://scripts/testing/buildings/CitadelMarketRigidTransformContract.gd"

## CPU publisher-payload diagnostic ONLY. Run later under the existing watchdog
## (100s intended outer limit); this file neither launches nor integrates scenes.
## Inputs: VOXEL_ROOF_INTEGRATION_BASELINE; output: VOXEL_MARKET_OVERLAP_REPORT
## (new absolute JSON path with an existing parent). No candidate/pose input.
## Reuse the preparation helper's producer/seat discovery, never its scene _ready.
const FramePreparation = preload("res://scripts/testing/buildings/CitadelMarketRecipeVisual.gd")
const HouseholdBatch = preload("res://scripts/buildings/HouseholdLayoutBatchRecipe.gd")


class CpuMeshBatchPublisher:
	extends "res://scripts/buildings/BuildingPartPublisher.gd"

	var captured_mesh_batches: Dictionary = {}

	func add_mesh_batch(parent: Node3D, mesh: Mesh, transforms: Array, material: Material, node_name: String, custom_data_override: Array = []) -> MultiMeshInstance3D:
		# Intercept the ACTUAL arguments generated by inherited publish_visual.
		# No recipe replay, replacement builder, buffer/instance readback, or
		# altered call arguments. Transform3D values are copied before super.
		var captured := {"mesh": mesh, "transforms": transforms.duplicate(),
			"collecting": static_visual_collecting, "partTransform": static_visual_part_transform,
			"customDataOverride": custom_data_override.duplicate(), "material": material,
			"parentId": parent.get_instance_id(), "nodeName": node_name, "matched": false}
		var instance := super.add_mesh_batch(parent, mesh, transforms, material, node_name, custom_data_override)
		if instance != null:
			captured_mesh_batches[instance.get_instance_id()] = captured
		return instance


const SOFT_LIMIT_MSEC := 80000
const MAX_SOURCE_PARTS := 10000
const MAX_PUBLISHED_PRIMITIVES := 1500000
const MAX_PRIMITIVE_TESTS := 2000000
const MAX_RECORDED_CONTACTS := 12000
const ROUNDING_GUARD := 1.0e-10
var _overlap_path := ""
var _started_msec := 0
var _next_progress_msec := 0
var _stop_reason := ""
var _counts := {"publishedParts": 0, "publishedPrimitives": 0, "partPairs": 0,
	"primitiveTests": 0, "satTests": 0, "recordedContacts": 0, "sourceHiddenParts": 0}
var _pair_rows: Array = []
var _inventory: Array = []
var _active_mesh_capture: CpuMeshBatchPublisher


func _run() -> void:
	_started_msec = Time.get_ticks_msec()
	_next_progress_msec = _started_msec + 10000
	_overlap_path = OS.get_environment("VOXEL_MARKET_OVERLAP_REPORT").strip_edges().simplify_path()
	if not _overlap_path.is_absolute_path() or _overlap_path.get_extension().to_lower() != "json" or FileAccess.file_exists(_overlap_path):
		push_error("Require a new absolute VOXEL_MARKET_OVERLAP_REPORT JSON path")
		quit(2)
		return
	var path := OS.get_environment("VOXEL_ROOF_INTEGRATION_BASELINE").strip_edges().simplify_path()
	var report := {"evidenceLevel": "source_only_actual_CPU_publisher_payload_overlap_diagnostic",
		"baselinePath": path, "baselineSha256": MARKET_FROZEN_SHA,
		"placementAccepted": false, "passed": false, "diagnosticCompleted": false,
		"scope": "Every moved household member, new/changed terminal source record, and unchanged terminal awning strip against all other blueprint source parts in both publications. Includes cross-household, frame/frame and unchanged terminal-cloth pairs; excludes only same-household internal pairs and other unchanged/unchanged pairs.",
		"method": "Actual publisher primitive envelopes first; affine-box SAT for box/box candidates; non-box mesh AABB candidates remain conservative. Source AABBs are NEVER used to cull publisher geometry.",
		"meshBatchInterception": "Diagnostic-only subclass copies actual add_mesh_batch mesh/transform arguments, then calls super unchanged. Returned nodes match captures by object identity; CPU mesh/count/parent fields are checked. Instance transforms use the base method's collecting-space composition. No MultiMesh buffer/get_instance_transform readback and no GPU-upload/draw proof. Box batches retain the existing CPU collector.",
		"doesNotProve": "No mesh triangle intersection for non-boxes, GPU/shader deformation, live collision, structural acceptance, traversal, NPC/navigation, terrain, tree meshes, or separately published furnishing-plan geometry. Closed source door pose only. Joinery/support contact is reported, not adjudicated as a defect. Complete scoped separation is not whole-world acceptance.",
		"numericPolicy": "Bounds use scalar-double interval sums from represented CPU payload values, outward-expanded by 1e-10 times coordinate magnitude. Existing affine SAT retains shear and skips near-zero axes; a separating axis certifies separation, but nonseparation is conservatively a box candidate, not an exact mesh-intersection assertion. Gaps inside the same guard remain unresolved; no clearance allowance or nominal-source repair.",
		"limits": {"softMsec": SOFT_LIMIT_MSEC, "sourceParts": MAX_SOURCE_PARTS,
			"publishedPrimitives": MAX_PUBLISHED_PRIMITIVES, "primitiveTests": MAX_PRIMITIVE_TESTS, "recordedContacts": MAX_RECORDED_CONTACTS,
			"note": "Cooperative limits checked between publications/pairs. An individual producer call is not preemptible; outer process watchdog remains required."}}
	if not path.is_absolute_path() or FileAccess.get_sha256(path) != MARKET_FROZEN_SHA:
		_finish_overlap(report, "frozen_sha_mismatch")
		return
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		_finish_overlap(report, "frozen_open_failed")
		return
	var envelope = file.get_var(false)
	var read_ok := file.get_error() == OK and file.get_position() == file.get_length()
	file.close()
	if not read_ok or not envelope is Dictionary or not envelope.get("output") is Dictionary:
		_finish_overlap(report, "invalid_frozen_envelope")
		return
	var frozen: Dictionary = envelope.output
	var source: Dictionary = frozen.get("sourceSnapshot", {})
	if source.is_empty() or source.parts.size() > MAX_SOURCE_PARTS:
		_finish_overlap(report, "invalid_or_oversized_source")
		return
	var before = Blueprint.new(source.id, source.seed, source.style)
	before.recipe = source.recipe.duplicate(true)
	before.rooms = source.rooms.duplicate(true)
	for record in source.parts:
		var part = before.add_part(record)
		if before.physical_parts_by_id.has(part.id):
			_finish_overlap(report, "duplicate_source_id")
			return
		before.physical_parts_by_id[part.id] = part
	var original_digest := _stable_digest(before.snapshot())
	if original_digest != _stable_digest(source):
		_finish_overlap(report, "frozen_roundtrip_mismatch")
		return
	var specs: Array = before.recipe.get("urbanPoc", {}).get("marketStalls", [])
	if specs.size() < 3:
		_finish_overlap(report, "missing_third_household_recipe")
		return
	var variation := float(before.seed % 19) / 100.0 - 0.09
	var members: Dictionary = {}
	var households: Array = []
	var internal_pairs := 0
	for spec in specs:
		var scratch = Blueprint.new("producer_membership_only", before.seed, before.style)
		UrbanRecipe.add_market_stall_household(scratch, Vector3.ZERO, float(spec.side), float(spec.depth), variation + float(spec.get("variation", 0.0)))
		var ids: Array = []
		for part in scratch.parts:
			if before.find_part(part.id) == null or members.has(part.id):
				_finish_overlap(report, "producer_membership_mismatch")
				return
			members[part.id] = households.size()
			ids.append(part.id)
		households.append({"memberIds": ids, "front": Vector3(0, 0, -float(spec.depth))})
		internal_pairs += ids.size() * (ids.size() - 1) / 2
	var combined = _copy_blueprint(before)
	var preparation: Dictionary = _prepare_households(combined, households)
	report["householdPreparation"] = preparation
	if not preparation.get("ready", false):
		_finish_overlap(report, "household_preparation_failed")
		return
	var changed_contents: Array = preparation.get("changedPartIds", [])
	internal_pairs = 0
	for household in households:
		var unchanged_count: int = household.memberIds.filter(func(id): return not changed_contents.has(id)).size()
		internal_pairs += unchanged_count * (unchanged_count - 1) / 2
	if not changed_contents.is_empty():
		report["scope"] += " Changed storage is also checked against every own-household part; only unchanged/unchanged internal pairs stay excluded."
	var furniture_obstacles: Array = FramePreparation._frozen_furnishing_obstacles(frozen)
	var furniture_reservations: Array[Rect2] = []
	for obstacle in furniture_obstacles:
		var bounds: AABB = obstacle.bounds
		furniture_reservations.append(Rect2(Vector2(bounds.position.x, bounds.position.z), Vector2(bounds.size.x, bounds.size.z)))
	var layout: Dictionary = HouseholdBatch.plan(combined, households, UrbanRecipe.plan_courtyard_household, furniture_reservations)
	report["layout"] = layout
	if not bool(layout.get("ready", false)):
		_finish_overlap(report, "shared_recipe_not_ready")
		return
	for placement in layout.households:
		var rigid: Transform3D = placement.transform
		for id in placement.memberIds:
			var part = combined.find_part(id)
			var transformed: Transform3D = rigid * combined.part_transform(part)
			part.position = transformed.origin
			part.rotation = transformed.basis.get_euler()
	# Match the headed fixture's deterministic cohort order. No obsolete market
	# geometry is excluded: all three markets move before terminal placement.
	var terminals: Dictionary = FramePreparation._prepare_terminal_frames(combined, variation, furniture_obstacles, layout.households)
	report["terminals"] = terminals
	if not bool(terminals.get("ready", false)) or terminals.get("setups", []).size() != 3:
		_finish_overlap(report, "terminal_construction_failed")
		return
	var augmentation: Dictionary = _augment_candidate(combined, layout.households)
	report["augmentation"] = augmentation
	if not augmentation.get("ready", false):
		_finish_overlap(report, "augmentation_failed")
		return
	if OS.get_environment("VOXEL_MARKET_PUBLISH_INTEGRATED") == "1":
		# Publish the actual freshly generated production result, not the
		# diagnostic composition above. That composition supplies the unchanged
		# comparison/membership scope only; exact equality is mandatory first.
		var castle_script := preload("res://scripts/buildings/CastleCompoundBlueprintBuilder.gd")
		var fixture: Dictionary = frozen.fixture
		var integrated = castle_script.build(fixture.seed, {"biome": fixture.biome, "siteKey": fixture.siteKey, "citadelScale": fixture.citadelScale})
		if integrated == null or UrbanRecipe.compose(integrated, fixture.seed) == null:
			_finish_overlap(report, "integrated_generation_failed")
			return
		if _stable_digest(integrated.snapshot()) != _stable_digest(combined.snapshot()):
			_finish_overlap(report, "integrated_source_mismatch")
			return
		combined = integrated
		report["candidateAuthority"] = "fresh CastleCompoundBlueprintBuilder -> CitadelUrbanPocComposer"
		report["integratedSourceExactlyMatchesDiagnosticComposition"] = true
	var added_ids: Array = augmentation.get("partIds", [])
	if not added_ids.is_empty():
		report["scope"] += " Also every new canopy frame member against all source parts, including its own household contents and other frame members; no new-frame/internal pairs are excluded."
	var active := members.duplicate()
	var changed_frames: Array = []
	var new_frames: Array = []
	var unchanged_awning_ids: Array = []
	for part in combined.parts:
		combined.physical_parts_by_id[part.id] = part
		var old = before.find_part(part.id)
		if members.has(part.id):
			continue
		# Check whether existing cloth already crosses neighbouring cloth before
		# prescribing a support-rail redesign. Ownership comes from the producer.
		if part.semantic == "citadel_terminal_shop_awning" and terminals.allIds.has(part.id):
			active[part.id] = true
			unchanged_awning_ids.append(part.id)
		if old == null or _stable_digest(old.snapshot()) != _stable_digest(part.snapshot()):
			if not terminals.allIds.has(part.id) and not added_ids.has(part.id):
				_finish_overlap(report, "unexpected_source_change")
				return
			active[part.id] = true
			if terminals.allIds.has(part.id):
				changed_frames.append(part.id)
				if old == null:
					new_frames.append(part.id)
	if combined.parts.size() > MAX_SOURCE_PARTS or combined.physical_parts_by_id.size() != combined.parts.size():
		_finish_overlap(report, "invalid_combined_source")
		return
	report["householdIds"] = members.keys()
	report["changedOrNewTerminalIds"] = changed_frames
	report["newTerminalIds"] = new_frames
	report["unchangedAwningInspectionIds"] = unchanged_awning_ids
	report["baselinePhysicalValidation"] = frozen.get("physicalValidation", {})
	report["physicalGateAccepted"] = false
	var combined_digest := _stable_digest(combined.snapshot())
	report["satHelperControls"] = _sat_controls()
	if not bool(report.satHelperControls.passed):
		_finish_overlap(report, "sat_helper_controls_failed")
		return
	var baseline_publisher = _configured_publisher(before)
	var combined_publisher = _configured_publisher(combined)
	var active_ids: Array = active.keys()
	active_ids.sort()
	var old_payloads: Dictionary = {}
	var new_payloads: Dictionary = {}
	for id in active_ids:
		if not _within_budget():
			break
		old_payloads[id] = _extract_overlap_payload(baseline_publisher, before, before.find_part(id), "baseline")
		new_payloads[id] = _extract_overlap_payload(combined_publisher, combined, combined.find_part(id), "combined")
	if not _stop_reason.is_empty():
		_finish_overlap(report, _stop_reason)
		return
	for first in range(active_ids.size()):
		for second in range(first + 1, active_ids.size()):
			var a: String = active_ids[first]
			var b: String = active_ids[second]
			if members.has(a) and members.has(b) and members[a] == members[b] and not changed_contents.has(a) and not changed_contents.has(b):
				continue
			_compare_overlap_pair(a, b, old_payloads[a], old_payloads[b], new_payloads[a], new_payloads[b],
				"canopy_frame_household" if (added_ids.has(a) and members.has(b)) or (added_ids.has(b) and members.has(a)) else ("canopy_frame_active" if added_ids.has(a) or added_ids.has(b) else ("household_household" if members.has(a) and members.has(b) else ("household_terminal" if members.has(a) or members.has(b) else "terminal_terminal"))))
			if not _within_budget():
				break
		if not _within_budget():
			break
	var surrounding_ids: Array = before.physical_parts_by_id.keys()
	surrounding_ids.sort()
	for id in surrounding_ids:
		if not _within_budget():
			break
		if active.has(id):
			continue
		# Publish BOTH versions even for identical records: publication context
		# can alter world-position weathering. Stream and release distant parts.
		var old: Dictionary = _extract_overlap_payload(baseline_publisher, before, before.find_part(id), "baseline")
		var current: Dictionary = _extract_overlap_payload(combined_publisher, combined, combined.find_part(id), "combined")
		for affected in active_ids:
			_compare_overlap_pair(affected, id, old_payloads[affected], old, new_payloads[affected], current,
				"canopy_frame_surrounding" if added_ids.has(affected) else ("household_surrounding" if members.has(affected) else "terminal_surrounding"))
			if not _within_budget():
				break
	if not _stop_reason.is_empty():
		_finish_overlap(report, _stop_reason)
		return
	var preserved := original_digest == _stable_digest(before.snapshot()) and combined_digest == _stable_digest(combined.snapshot()) and FileAccess.get_sha256(path) == MARKET_FROZEN_SHA
	report["sourceAndFrozenFileUnchangedByPublication"] = preserved
	if not preserved:
		_finish_overlap(report, "publication_mutated_source")
		return
	var surrounding_count: int = combined.parts.size() - active_ids.size()
	var expected_pairs: int = active_ids.size() * surrounding_count + active_ids.size() * (active_ids.size() - 1) / 2 - internal_pairs
	report["expectedPartPairs"] = expected_pairs
	report["expectedPartPublicationsIncludingSourceHidden"] = before.parts.size() + combined.parts.size()
	if _counts.partPairs != expected_pairs or _counts.publishedParts != before.parts.size() + combined.parts.size():
		_finish_overlap(report, "incomplete_pair_or_publication_coverage")
		return
	_finish_overlap(report, "diagnostic_complete")


func _augment_candidate(_blueprint, _plans: Array) -> Dictionary:
	# Default runner retains its previous scope. A separate explicitly named
	# canopy fixture calls the shared recipe and expands coverage, never omits it.
	return {"ready": true, "partIds": []}


func _prepare_households(_blueprint, _households: Array) -> Dictionary:
	return {"ready": true}


func _extract_overlap_payload(publisher, blueprint, part, phase: String) -> Dictionary:
	if part == null:
		return {"status": "absent_in_baseline", "primitives": [], "bounds": []}
	_counts.publishedParts += 1
	if not bool(part.recipe.get("visual", true)):
		_counts.sourceHiddenParts += 1
		_inventory.append({"phase": phase, "partId": part.id, "status": "source_visual_false", "primitiveCount": 0})
		return {"status": "source_visual_false", "primitives": [], "bounds": []}
	# The inherited helper captures box transforms before MultiMesh upload and
	# traverses actual published non-box nodes. No physics/scene registration.
	var captured: Dictionary = _complete_payload(publisher, blueprint, part)
	var result := {"status": "published", "primitives": [], "bounds": []}
	for primitive in captured.primitives:
		var transform: Transform3D = primitive.transform
		var local := AABB(Vector3(-0.5, -0.5, -0.5), Vector3.ONE) if primitive.type == "box" else (primitive.meshBounds as AABB)
		if not _valid_box(transform) or not local.position.is_finite() or not local.size.is_finite() or local.size == Vector3.ZERO or local.size.x < 0 or local.size.y < 0 or local.size.z < 0:
			captured.errors.append("invalid_published_primitive:" + String(primitive.id))
			continue
		var bounds := _payload_intervals(transform, local)
		var row := {"id": primitive.id, "type": primitive.type, "transform": transform,
			"localMeshBounds": local, "bounds": bounds}
		result.primitives.append(row)
		result.bounds = _union_intervals(result.bounds, bounds)
	_counts.publishedPrimitives += captured.primitives.size()
	_inventory.append({"phase": phase, "partId": part.id, "kind": part.kind, "semantic": part.semantic,
		"boxCount": captured.boxCount, "nonBoxCount": captured.nonBoxCount,
		"payloadBounds": result.bounds, "errors": captured.errors,
		"cpuMeshBatchCaptures": captured.get("cpuMeshBatchCaptures", [])})
	if not captured.errors.is_empty() or captured.primitives.is_empty():
		_stop_reason = "incomplete_or_invalid_publisher_payload"
	_within_budget()
	return result


func _configured_publisher(blueprint):
	var publisher := CpuMeshBatchPublisher.new()
	publisher.source_blueprint_id = publisher.canonical_source_blueprint_id(blueprint)
	publisher.surface_history.configure(blueprint.recipe, blueprint.parts)
	publisher.paving_treatments = blueprint.recipe.get("pavingTreatments", [])
	return publisher


func _complete_payload(publisher, blueprint, part) -> Dictionary:
	_active_mesh_capture = publisher as CpuMeshBatchPublisher
	_active_mesh_capture.captured_mesh_batches.clear()
	# Super still owns publication, ordinary box collection, mesh traversal and
	# temporary-node disposal. Its recursive traversal dispatches the override
	# below, replacing ONLY errors for identity-matched captured MultiMeshes.
	var result: Dictionary = super._complete_payload(publisher, blueprint, part)
	for captured in _active_mesh_capture.captured_mesh_batches.values():
		if not bool(captured.matched):
			result.errors.append("unmatched_cpu_mesh_batch:" + String(captured.nodeName))
	_active_mesh_capture.captured_mesh_batches.clear()
	_active_mesh_capture = null
	return result


func _collect_nonboxes(parent: Node, accumulated: Transform3D, prefix: String, result: Dictionary) -> void:
	# Preserve the inherited MeshInstance3D path, including fail-closed errors
	# for unavailable vertex arrays. Uncaptured MultiMeshes also remain errors.
	super._collect_nonboxes(parent, accumulated, prefix, result)
	for child in parent.get_children():
		if not child is MultiMeshInstance3D or _active_mesh_capture == null:
			continue
		var path := prefix + "/" + String(child.name)
		var captured: Dictionary = _active_mesh_capture.captured_mesh_batches.get(child.get_instance_id(), {})
		if captured.is_empty():
			continue
		captured.matched = true
		var mesh: Mesh = captured.mesh
		var local_transforms: Array = captured.transforms
		var multimesh: MultiMesh = child.multimesh
		# These are resource-owned CPU fields, not RenderingServer instance data.
		if multimesh == null or mesh == null or multimesh.mesh != mesh or multimesh.instance_count != local_transforms.size() or multimesh.transform_format != MultiMesh.TRANSFORM_3D or multimesh.visible_instance_count != -1 or captured.parentId != parent.get_instance_id() or child.material_override != captured.material:
			result.errors.append("cpu_mesh_batch_node_contract_mismatch:" + path)
			continue
		if local_transforms.is_empty() or mesh.get_surface_count() == 0:
			result.errors.append("empty_cpu_mesh_batch:" + path)
			continue
		var mesh_bounds := mesh.get_aabb()
		if not mesh_bounds.position.is_finite() or not mesh_bounds.size.is_finite() or mesh_bounds.size == Vector3.ZERO:
			result.errors.append("unavailable_cpu_mesh_batch_bounds:" + path)
			continue
		# Only the actual unit BoxMesh receives exact affine-box treatment;
		# other mesh types retain their conservative transformed mesh bounds.
		var unit_box_mesh := mesh is BoxMesh and (mesh as BoxMesh).size == Vector3.ONE
		var node_transform: Transform3D = accumulated * child.transform
		var valid := true
		for index in range(local_transforms.size()):
			if not local_transforms[index] is Transform3D:
				result.errors.append("invalid_cpu_mesh_batch_transform:" + path)
				valid = false
				break
			var instance_transform: Transform3D = local_transforms[index]
			if bool(captured.collecting):
				# Same multiplication/order as add_mesh_batch before its setter.
				instance_transform = (captured.partTransform as Transform3D) * instance_transform
			var world_transform := node_transform * instance_transform
			result.primitives.append({"id": "cpu_multimesh:" + path + ":%d" % index,
				"type": "box" if unit_box_mesh else "mesh", "transform": world_transform,
				"meshBounds": mesh_bounds, "meshClass": mesh.get_class(),
				"captureBoundary": "add_mesh_batch_arguments_before_unchanged_super"})
			if unit_box_mesh:
				result.boxCount += 1
			else:
				result.nonBoxCount += 1
		if not valid:
			continue
		# Erase only the precise unsupported-node error we have now covered.
		# Missing interception/dynamic dispatch can therefore never pass silently.
		result.errors.erase("unsupported_nonbox_multimesh:" + path)
		if not result.has("cpuMeshBatchCaptures"):
			result["cpuMeshBatchCaptures"] = []
		result.cpuMeshBatchCaptures.append({"path": path, "instanceCount": local_transforms.size(),
			"meshClass": mesh.get_class(), "actualUnitBoxMesh": unit_box_mesh,
			"argumentTransformDigest": _stable_digest(local_transforms), "partTransform": captured.partTransform,
			"collecting": captured.collecting, "customDataOverrideCount": captured.customDataOverride.size(),
			"instanceNodeMatched": true, "gpuReadbackUsed": false})


func _material_digest(_material: Variant) -> String:
	# Overlap-only specialization: material hashing is irrelevant and expensive
	# for thousands of surroundings. No material-preservation claim is made.
	return "not_compared_in_overlap_diagnostic"


func _compare_overlap_pair(a: String, b: String, old_a: Dictionary, old_b: Dictionary, new_a: Dictionary, new_b: Dictionary, category: String) -> void:
	if not _within_budget():
		return
	_counts.partPairs += 1
	var before := _classify_overlap(old_a, old_b)
	var after := _classify_overlap(new_a, new_b)
	if before.get("candidates", []).is_empty() and after.get("candidates", []).is_empty() and not bool(before.get("broadphaseCandidate", false)) and not bool(after.get("broadphaseCandidate", false)):
		return
	var previous_clear: bool = before.status in ["certified_separated", "absent_in_baseline", "source_visual_false"]
	var new_candidate: bool = not after.candidates.is_empty()
	_pair_rows.append({"aPartId": a, "bPartId": b, "category": category, "baseline": before, "combined": after,
		"newlyIntroducedPartPairCandidate": previous_clear and new_candidate,
		"newlyIntroducedBoxSatCandidate": previous_clear and after.candidates.any(func(row): return row.classification == "box_sat_nonseparated_candidate"),
		"comparisonScope": "Part-pair introduction only. Primitive IDs locate payloads within each publication; material grouping/order is not assumed stable across publication. Existing candidate pairs retain both complete candidate lists for review, not an automatic no-regression verdict."})


func _classify_overlap(a: Dictionary, b: Dictionary) -> Dictionary:
	var result := {"status": "certified_separated", "broadphaseCandidate": false, "candidates": [], "satSeparatedPairs": 0}
	if a.status != "published" or b.status != "published":
		result.status = a.status if a.status != "published" else b.status
		return result
	if _intervals_separate(a.bounds, b.bounds):
		return result
	result.broadphaseCandidate = true
	for first in a.primitives:
		for second in b.primitives:
			_counts.primitiveTests += 1
			if not _within_budget():
				result.status = "incomplete"
				return result
			if _intervals_separate(first.bounds, second.bounds):
				continue
			var kind := "nonbox_conservative_potential_intersection"
			var gap: Variant = null
			if first.type == "box" and second.type == "box":
				_counts.satTests += 1
				gap = _separation(first.transform, second.transform)
				var guard := _interval_guard(first.bounds, second.bounds)
				if float(gap) > guard:
					result.satSeparatedPairs += 1
					continue
				kind = "box_sat_nonseparated_candidate" if float(gap) < -guard else "box_contact_or_numerically_unresolved"
			_counts.recordedContacts += 1
			if not _within_budget():
				result.status = "incomplete"
				return result
			result.candidates.append({"aPrimitive": first, "bPrimitive": second, "classification": kind,
				"boxSatGreatestAxisGap": gap, "notAutomaticallyADefect": true})
	if not result.candidates.is_empty():
		result.status = "review_required"
	return result


func _payload_intervals(transform: Transform3D, local: AABB) -> Array:
	# Avoid float32 Vector3 corner accumulation shrinking a broad-phase bound.
	var result: Array = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
	for axis in range(3):
		var lower := float(transform.origin[axis])
		var upper := lower
		for component in range(3):
			var coefficient := float(transform.basis[component][axis])
			var p := float(local.position[component])
			var q := p + float(local.size[component])
			lower += minf(coefficient * p, coefficient * q)
			upper += maxf(coefficient * p, coefficient * q)
		var guard := ROUNDING_GUARD * maxf(1.0, maxf(absf(lower), absf(upper)))
		result[axis] = lower - guard
		result[axis + 3] = upper + guard
	return result


func _union_intervals(a: Array, b: Array) -> Array:
	if a.is_empty():
		return b.duplicate()
	var result := a.duplicate()
	for axis in range(3):
		result[axis] = minf(a[axis], b[axis])
		result[axis + 3] = maxf(a[axis + 3], b[axis + 3])
	return result


func _intervals_separate(a: Array, b: Array) -> bool:
	for axis in range(3):
		if float(a[axis + 3]) < float(b[axis]) or float(b[axis + 3]) < float(a[axis]):
			return true
	return false


func _interval_guard(a: Array, b: Array) -> float:
	var magnitude := 1.0
	for value in a + b:
		magnitude = maxf(magnitude, absf(float(value)))
	return ROUNDING_GUARD * magnitude


func _within_budget() -> bool:
	if not _stop_reason.is_empty():
		return false
	var now := Time.get_ticks_msec()
	if now - _started_msec > SOFT_LIMIT_MSEC:
		_stop_reason = "soft_time_limit_exceeded"
	elif _counts.publishedPrimitives > MAX_PUBLISHED_PRIMITIVES:
		_stop_reason = "published_primitive_limit_exceeded"
	elif _counts.primitiveTests > MAX_PRIMITIVE_TESTS:
		_stop_reason = "primitive_comparison_limit_exceeded"
	elif _counts.recordedContacts > MAX_RECORDED_CONTACTS:
		_stop_reason = "report_contact_limit_exceeded"
	if now >= _next_progress_msec:
		print("market published overlap: ", _counts, " elapsedMsec=", now - _started_msec)
		_next_progress_msec = now + 10000
	return _stop_reason.is_empty()


func _finish_overlap(report: Dictionary, status: String) -> void:
	var completed := status == "diagnostic_complete" and _stop_reason.is_empty()
	var outstanding: Array = _pair_rows.filter(func(row): return not row.combined.candidates.is_empty())
	report["status"] = status
	report["diagnosticCompleted"] = completed
	report["passed"] = completed and outstanding.is_empty()
	report["passMeaning"] = "Completed scoped CPU-payload non-overlap certificate only; any touch/potential/box overlap leaves passed=false. Diagnostic completion alone is not acceptance."
	report["allScopedCombinedPairsCertifiedSeparated"] = completed and outstanding.is_empty()
	report["pairComparisons"] = _pair_rows
	report["newlyIntroducedPartPairCandidates"] = _pair_rows.filter(func(row): return row.newlyIntroducedPartPairCandidate).map(func(row): return {"aPartId": row.aPartId, "bPartId": row.bPartId, "category": row.category})
	report["newlyIntroducedBoxSatCandidates"] = _pair_rows.filter(func(row): return row.newlyIntroducedBoxSatCandidate).map(func(row): return {"aPartId": row.aPartId, "bPartId": row.bPartId, "category": row.category})
	report["payloadInventory"] = _inventory
	report["counts"] = _counts
	report["elapsedMsec"] = Time.get_ticks_msec() - _started_msec
	var output := FileAccess.open(_overlap_path, FileAccess.WRITE)
	if output == null:
		push_error("Cannot write published overlap report")
		quit(2)
		return
	output.store_string(JSON.stringify(_overlap_json(report), "\t"))
	output.flush()
	var error := output.get_error()
	output.close()
	print("VOXEL_MARKET_OVERLAP_REPORT ", _overlap_path, " status=", status)
	quit(2 if error != OK or not completed else (0 if report.passed else 1))


func _overlap_json(value: Variant) -> Variant:
	if value is Rect2:
		return {"position": [value.position.x, value.position.y], "size": [value.size.x, value.size.y]}
	if value is Dictionary:
		var result: Dictionary = {}
		for key in value:
			result[key] = _overlap_json(value[key])
		return result
	if value is Array:
		return value.map(func(item): return _overlap_json(item))
	return _report_value(value)
