extends RefCounted
class_name NpcConstants

const ARCHITECTURE_VERSION := "phase07_local_avoidance"
const LEGACY_LOCOMOTION_MODE := "legacy_route_intent_motor_adapter"

const CELL_SIZE := 1.35
const NAV_TILE_CELL_SIZE := 16
const NAV_BUILD_MAX_JOBS_PER_TICK := 1
const NAV_BUILD_HARD_SLICE_USEC := 4000
const ROUTE_SEARCH_MAX_EXPANSIONS_PER_TICK := 128
const ROUTE_SEARCH_COMPATIBILITY_EXPANSIONS := 200000
const ROUTE_REQUEST_QUEUE_CAPACITY := 256
const ROUTE_COMPLETED_RESULT_CAPACITY := 512
const ROUTE_ACTIVE_JOB_CAPACITY := 256
const ROUTE_LOCAL_COST_CACHE_CAPACITY := 2048
const ROUTE_REPAIR_FAILURE_LIMIT := 3
const ROUTE_REPAIR_FAILURE_HISTORY_CAPACITY := 256
const DOOR_QUEUE_INHERITANCE_SECONDS := 0.35
const DOOR_PRIVATE_CLOSE_DELAY_SECONDS := 0.35
const DOOR_BLOCKED_CLOSE_RETRY_SECONDS := 0.25
const DOOR_TRACE_CAPACITY := 96
const AVOIDANCE_RADIUS_SAFETY_MARGIN := 0.08
const AVOIDANCE_NEIGHBOR_DISTANCE := 4.5
const AVOIDANCE_MAX_NEIGHBORS := 8
const AVOIDANCE_TIME_HORIZON_AGENTS := 1.2
const AVOIDANCE_TIME_HORIZON_OBSTACLES := 0.8
const AVOIDANCE_ACTIVE_DISTANCE := 5.0
const AVOIDANCE_CALLBACK_STALE_FRAMES := 1
const AVOIDANCE_TERMINAL_DIRECT_DISTANCE := CELL_SIZE * 1.35
const AVOIDANCE_PORTAL_LATERAL_SCALE := 0.0
const PORTAL_RECENTER_DISTANCE_SCALE := 0.35
const PORTAL_RETREAT_DISTANCE_SCALE := 0.45
const CORRIDOR_LOOKAHEAD_MIN_DISTANCE := 0.72
const CORRIDOR_LOOKAHEAD_MAX_DISTANCE := 2.70
const CORRIDOR_LATERAL_TOLERANCE := 0.52
const CORRIDOR_PORTAL_LATERAL_TOLERANCE := 0.16
const CORRIDOR_TURN_SLOW_ANGLE_DEGREES := 42.0
const CORRIDOR_TURN_SLOW_FACTOR := 0.58
const CORRIDOR_TURN_WAYPOINT_CLEARANCE := CELL_SIZE * 0.38
const CORRIDOR_ACTION_SLOW_DISTANCE := 1.70
const CORRIDOR_ARRIVAL_STOP_RADIUS := 0.28
const CORRIDOR_PROGRESS_EPSILON := 0.025
const CORRIDOR_NO_PROGRESS_TICKS := 18
const CORRIDOR_OSCILLATION_SIGN_EPSILON := 0.08

const TELEMETRY_RING_CAPACITY := 256
const TELEMETRY_GLOBAL_COUNTER_LIMIT := 128
const BRAIN_UPDATES_PER_TICK := 8
const BRAIN_REGISTERED_AGENT_LIMIT := 256
const CHANGE_BUS_MAX_PENDING_TILES := 512

# Existing layer values observed before Phase 01. These are documentation constants,
# not a renumbering of physics layers.
const COLLISION_WORLD_QUERY := 1
const COLLISION_TERRAIN_BODY := 2
const COLLISION_NPC_BODY := 4
const COLLISION_NONBLOCKING_PATH := 8
const COLLISION_HOSTILE_LOS_MASK := 1 | 4
const COLLISION_NPC_STATIC_QUERY_MASK := 1
const COLLISION_PLAYER_BODY := 1
const COLLISION_NPC_BODY_MASK := 1 | 2 | 4
const COLLISION_NPC_SAFE_PLACEMENT_MASK := 1 | 2 | 4

const DEFAULT_NPC_RADIUS := 0.42
const DEFAULT_NPC_STANDING_HEIGHT := 1.72
const DEFAULT_NPC_STEP_UP := 1.24
const DEFAULT_NPC_SAFE_DROP := 1.55
const DEFAULT_NPC_MAX_FLOOR_ANGLE_DEGREES := 46.0
const DEFAULT_NPC_WALK_SPEED := 2.45
const DEFAULT_NPC_ACCELERATION := 14.0
const DEFAULT_DOOR_MINIMUM_WIDTH := 0.78
const DEFAULT_HEADROOM_MARGIN := 0.08
const DEFAULT_PERSONAL_SPACE_MARGIN := 0.10
const TRAFFIC_RETREAT_CLEARANCE := DEFAULT_NPC_RADIUS * 2.0 + DEFAULT_PERSONAL_SPACE_MARGIN
const TRAFFIC_RETREAT_DISTANCE_SCALE := 0.45

