extends RefCounted
class_name NpcConstants

const ARCHITECTURE_VERSION := "phase04_hierarchical_routing"
const LEGACY_LOCOMOTION_MODE := "legacy_route_intent_motor_adapter"

const CELL_SIZE := 1.35
const NAV_TILE_CELL_SIZE := 16
const NAV_BUILD_MAX_JOBS_PER_TICK := 1
const NAV_BUILD_HARD_SLICE_USEC := 4000
const ROUTE_SEARCH_MAX_EXPANSIONS_PER_TICK := 128
const ROUTE_SEARCH_COMPATIBILITY_EXPANSIONS := 200000
const ROUTE_REQUEST_QUEUE_CAPACITY := 256
const ROUTE_COMPLETED_RESULT_CAPACITY := 512
const ROUTE_ACTIVE_JOB_CAPACITY := 256
const ROUTE_LOCAL_COST_CACHE_CAPACITY := 2048
const ROUTE_REPAIR_FAILURE_LIMIT := 3
const ROUTE_REPAIR_FAILURE_HISTORY_CAPACITY := 256

const TELEMETRY_RING_CAPACITY := 256
const TELEMETRY_GLOBAL_COUNTER_LIMIT := 128
const BRAIN_UPDATES_PER_TICK := 8
const BRAIN_REGISTERED_AGENT_LIMIT := 256
const CHANGE_BUS_MAX_PENDING_TILES := 512

# Existing layer values observed before Phase 01. These are documentation constants,
# not a renumbering of physics layers.
const COLLISION_WORLD_QUERY := 1
const COLLISION_TERRAIN_BODY := 2
const COLLISION_NPC_BODY := 4
const COLLISION_NONBLOCKING_PATH := 8
const COLLISION_HOSTILE_LOS_MASK := 1 | 4
const COLLISION_NPC_STATIC_QUERY_MASK := 1
const COLLISION_PLAYER_BODY := 1
const COLLISION_NPC_BODY_MASK := 1 | 2 | 4
const COLLISION_NPC_SAFE_PLACEMENT_MASK := 1 | 2 | 4

const DEFAULT_NPC_RADIUS := 0.42
const DEFAULT_NPC_STANDING_HEIGHT := 1.72
const DEFAULT_NPC_STEP_UP := 1.24
const DEFAULT_NPC_SAFE_DROP := 1.55
const DEFAULT_NPC_MAX_FLOOR_ANGLE_DEGREES := 46.0
const DEFAULT_NPC_WALK_SPEED := 2.45
const DEFAULT_NPC_ACCELERATION := 14.0
const DEFAULT_DOOR_MINIMUM_WIDTH := 0.78
const DEFAULT_HEADROOM_MARGIN := 0.08
const DEFAULT_PERSONAL_SPACE_MARGIN := 0.10

