param(
    [string]$ReportPath = "artifacts/true-3d-cave-biome-audit.json"
)

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $root

$rootPrefix = $root.TrimEnd("\") + "\"
$allScriptFiles = Get-ChildItem -LiteralPath (Join-Path $root "scripts") -Recurse -Filter "*.gd" |
    ForEach-Object { $_.FullName.Substring($rootPrefix.Length) }

$rules = @(
    [pscustomobject]@{
        Id = "heightfield-terrain-mesh"
        Files = @("scripts/MainPlaytestTools.gd")
        Pattern = "func terrain_surface_height_cell|func terrain_quad_hidden_for_cell|func add_chunk_skirts|func terrain_vertex_local|func terrain_normal_for_cell|surface_quad_hidden_for_cell3|terrain_quad_hidden_for_cell\("
        Requirement = "Terrain mesh must be extracted from authoritative (x,y,z) solid/air samples, not a heightfield with hidden cave quads."
        MigrationTarget = "Phase 2: replace heightfield chunk mesh with volume surface extraction."
    },
    [pscustomobject]@{
        Id = "block-face-terrain-mesh"
        Files = @("scripts/MainPlaytestTools.gd")
        Pattern = "func add_volume_face|func add_volume_quad|directions:\s*Array\[Vector3i\]"
        Requirement = "Terrain must keep the game's natural look; true 3D volume extraction must not regress to visible Minecraft-style cube faces."
        MigrationTarget = "Use continuous density isosurface extraction from the authoritative (x,y,z) sampler."
    },
    [pscustomobject]@{
        Id = "legacy-xz-generation-api"
        Files = @("scripts/MainPropFactory.gd", "scripts/MainInterface.gd")
        Pattern = "func height_at_world|func ground_height_at_world|func terrain_height_cell|func base_height_cell|func natural_base_height_cell|func biome_at_cell|func terrain_material_id_for_cell"
        Requirement = "No authoritative (x,z) terrain, biome, ground, or material generation APIs may remain."
        MigrationTarget = "Phase 1/5: replace callers with 3D samples or temporary adapter-only probes."
    },
    [pscustomobject]@{
        Id = "legacy-xz-generation-call-sites"
        Files = $allScriptFiles
        Pattern = "height_at_world|ground_height_at_world|terrain_height_cell|base_height_cell|natural_base_height_cell|(?<!surface_)\bbiome_at_cell\b|biome_at_cell3|terrain_material_id_for_cell"
        Requirement = "Tests and runtime systems must not call legacy (x,z) terrain, biome, ground, or material APIs."
        MigrationTarget = "Phase 5/6: call surface_y_at_position, ground_y_near_position, surface_y_at_cell(Vector3i), surface_biome_at_cell(Vector3i), or full volume samples."
    },
    [pscustomobject]@{
        Id = "world-generation-height-authority"
        Files = @("scripts/WorldGenerationSystem.gd")
        Pattern = "func surface_height_for_cell3|func edited_surface_height_for_cell3|func base_surface_height_for_cell3|func natural_surface_height_for_cell3|func surface_height_at_world|func surface_height_for_cell"
        Requirement = "World generation must be authoritative as density/solid/air/biome/material samples, with height derived only as a compatibility projection."
        MigrationTarget = "Phase 1: implement sample_cell/sample_world/density_at/solid_at/biome_at/material_at as the authority."
    },
    [pscustomobject]@{
        Id = "external-cave-plan-authority"
        Files = @("scripts/WorldGenerationSystem.gd", "scripts/SubsurfaceSystem.gd", "scripts/StructureSystem.gd")
        Pattern = "register_cave_plan|cave_plan_records|active_plans_from_records|cave_patch_plans|cave_active_plans|cave_records|generated_caves|func cave_plan_for_region|func make_cave_plan"
        Requirement = "Caves must be a biome/density field generated by the world sampler, not external plans placed into terrain."
        MigrationTarget = "Phase 1/3: move cave feature generation into WorldGenerationSystem samples and remove StructureSystem cave authority."
    },
    [pscustomobject]@{
        Id = "cave-mouth-patch-authority"
        Files = @("scripts/WorldGenerationSystem.gd", "scripts/SubsurfaceSystem.gd", "scripts/StructureSystem.gd", "scripts/CaveInteriorBuilder.gd")
        Pattern = "cave_mound_overlay|surface_patch_quad_cut_by_cave_pipe|cave_surface_point_opens_to_air|surface_quad_hidden_for_cell3|terrain_quad_hidden_for_cell|terrain_material_override_for_cell|cave_mouth_portal_cells|cave_terrain_pipe_cut_cells|cave_terrain_opening_cells|cave_mouth_"
        Requirement = "Cave mouth, tunnel, floor, ceiling, wall, terrain cut, mesh, and collision must come from one carved volume, with no mouth-specific patch/portal/rim/facade authority."
        MigrationTarget = "Phase 2/3/4: remove hidden quads, material overrides, and mouth-specific geometry helpers."
    },
    [pscustomobject]@{
        Id = "separate-cave-volume-mesh"
        Files = @("scripts/SubsurfaceSystem.gd", "scripts/CaveInteriorBuilder.gd")
        Pattern = "func rebuild_cave_patch|func build_cave_volume_mesh|func add_cave_volume_to_surface_tool|func add_cave_voxel_volume_to_surface_tool|func add_cave_surface_shell_to_surface_tool|SubsurfaceCaveVisual|SubsurfaceCaveBody|SubsurfaceCaveCollision|func build_visual_mesh|func build_collision_mesh|func add_carved_volume|rendered_shell_"
        Requirement = "Cave mesh and collision must be emitted by the same chunk volume extraction path as terrain, not by a separate cave shell/body."
        MigrationTarget = "Phase 2/4: delete separate cave shell/volume authority; keep only decoration helpers after volume exists."
    },
    [pscustomobject]@{
        Id = "structure-system-cave-builder"
        Files = $allScriptFiles
        Pattern = "build_cave|apply_cave_terrain_edits|cave_plan_for_region|cave_records_snapshot|find_cave_plan_sample|cave_terrain_mouth_summary|hiddenPortalCells|stoneOverridePortalCells|terrain_material_override_for_cell"
        Requirement = "StructureSystem and tests must not create or accept caves as placed structures, hidden portals, or material override patches."
        MigrationTarget = "Phase 3/6: query cave biome volumes, decorate after discovery, and fail tests on banned architecture."
    },
    [pscustomobject]@{
        Id = "height-edit-authority"
        Files = @("scripts/MainCore.gd", "scripts/MainSaveState.gd", "scripts/PlaytestRunner.gd", "scripts/testing/CaveGenerationTestRunner.gd", "scripts/testing/CaveVisualPlaytestRunner.gd", "scripts/visual/VisualCaptureRunner.gd")
        Pattern = "height_edits|snapshot_height_edits|restore_height_edits"
        Requirement = "Terrain edits must become deterministic 3D volume edits; height edits cannot remain generation authority."
        MigrationTarget = "Phase 1/5: migrate save/load and tests to volume edit samples."
    },
    [pscustomobject]@{
        Id = "surface-projection-direct-height-authority"
        Files = @("scripts/WorldGenerationSystem.gd")
        Pattern = "func surface_y_for_cell\(cell: Vector3i\) -> float: return base_surface_y_for_cell\(cell\)"
        Requirement = "Public surface helpers must be derived projections from the authoritative solid/air volume, not direct height authority."
        MigrationTarget = "Phase 5: surface_y_for_cell must scan volume samples for a solid/air boundary."
    }
)

$requiredRules = @(
    [pscustomobject]@{
        Id = "terrain-mesh-volume-sample-required"
        File = "scripts/MainPlaytestTools.gd"
        Pattern = "sample_world|density_at"
        Requirement = "Chunk terrain mesh generation must sample the authoritative (x,y,z) volume."
        MigrationTarget = "Phase 2: build_chunk_mesh must extract surfaces from WorldGenerationSystem density/sample queries."
    },
    [pscustomobject]@{
        Id = "world-generation-sample-api-required"
        File = "scripts/WorldGenerationSystem.gd"
        Pattern = "func sample_cell|func sample_world|func density_at|func solid_at|func biome_at|func material_at"
        Requirement = "WorldGenerationSystem must expose the required authoritative 3D sample API."
        MigrationTarget = "Phase 1: keep sample_cell/sample_world/density_at/solid_at/biome_at/material_at as the generation authority."
    },
    [pscustomobject]@{
        Id = "surface-projection-volume-scan-required"
        File = "scripts/WorldGenerationSystem.gd"
        Pattern = "func volume_surface_y_for_cell|sample_cell\(Vector3i\(cell.x, y, cell.z\)\)"
        Requirement = "Surface projection helpers must scan authoritative (x,y,z) solid/air samples."
        MigrationTarget = "Phase 5: derive surface_y_for_cell from volume_surface_y_for_cell."
    },
    [pscustomobject]@{
        Id = "terrain-mesh-solid-air-transition-required"
        File = "scripts/MainPlaytestTools.gd"
        Pattern = "extract_volume_iso_cube|extract_volume_iso_tetrahedron|interpolate_volume_iso_edge"
        Requirement = "Terrain mesh triangles must be emitted only where the authoritative volume density crosses the solid/air boundary."
        MigrationTarget = "Phase 2/6: build_chunk_mesh must extract a solid/air isosurface from 3D volume samples."
    },
    [pscustomobject]@{
        Id = "terrain-collision-from-mesh-required"
        File = "scripts/MainRuntimeTools.gd"
        Pattern = "create_trimesh_shape|terrain_mesh_create_trimesh_shape|volume_sample_extraction"
        Requirement = "Terrain collision must be built from the same mesh generated by volume extraction."
        MigrationTarget = "Phase 2/6: chunk_assets must use mesh.create_trimesh_shape and runtime chunks must expose matching geometry source metadata."
    }
)

$findings = @()
foreach ($rule in $rules) {
    foreach ($relativePath in $rule.Files) {
        $absolutePath = Join-Path $root $relativePath
        if (-not (Test-Path -LiteralPath $absolutePath)) {
            continue
        }
        $matches = Select-String -LiteralPath $absolutePath -Pattern $rule.Pattern -AllMatches
        foreach ($match in $matches) {
            $findings += [pscustomobject]@{
                ruleId = $rule.Id
                file = $relativePath.Replace("\", "/")
                line = $match.LineNumber
                text = $match.Line.Trim()
                pattern = $rule.Pattern
                requirement = $rule.Requirement
                migrationTarget = $rule.MigrationTarget
            }
        }
    }
}

foreach ($rule in $requiredRules) {
    $absolutePath = Join-Path $root $rule.File
    if (-not (Test-Path -LiteralPath $absolutePath)) {
        $findings += [pscustomobject]@{
            ruleId = $rule.Id
            file = $rule.File.Replace("\", "/")
            line = 0
            text = "missing file"
            pattern = $rule.Pattern
            requirement = $rule.Requirement
            migrationTarget = $rule.MigrationTarget
        }
        continue
    }
    $matches = Select-String -LiteralPath $absolutePath -Pattern $rule.Pattern -AllMatches
    if ($matches.Count -eq 0) {
        $findings += [pscustomobject]@{
            ruleId = $rule.Id
            file = $rule.File.Replace("\", "/")
            line = 0
            text = "required pattern missing"
            pattern = $rule.Pattern
            requirement = $rule.Requirement
            migrationTarget = $rule.MigrationTarget
        }
    }
}

$resolvedReportPath = if ([System.IO.Path]::IsPathRooted($ReportPath)) {
    $ReportPath
} else {
    Join-Path $root $ReportPath
}

$reportDirectory = Split-Path -Parent $resolvedReportPath
if ($reportDirectory -ne "" -and -not (Test-Path -LiteralPath $reportDirectory)) {
    New-Item -ItemType Directory -Force -Path $reportDirectory | Out-Null
}

$status = if ($findings.Count -eq 0) { "passed" } else { "failed" }
$report = [pscustomobject]@{
    schemaVersion = 1
    runnerId = "true_3d_cave_biome_static_audit"
    evidenceLevel = "static-audit"
    status = $status
    failureCount = $findings.Count
    ruleCount = $rules.Count
    requiredRuleCount = $requiredRules.Count
    generatedAtUtc = (Get-Date).ToUniversalTime().ToString("o")
    plan = "CODEX_TRUE_3D_CAVE_BIOME_PLAN.md"
    audit = "CODEX_TRUE_3D_CAVE_BIOME_AUDIT.md"
    findings = $findings
}

$report | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $resolvedReportPath -Encoding UTF8

if ($findings.Count -gt 0) {
    Write-Host ("true_3d_cave_biome_static_audit failed with {0} findings. Report: {1}" -f $findings.Count, $resolvedReportPath)
    exit 1
}

Write-Host ("true_3d_cave_biome_static_audit passed. Report: {0}" -f $resolvedReportPath)
exit 0
